version: '3.9'

services:

  postgres-dev-main:
    image: postgres:16
    container_name: postgres-dev-main

    environment:
      POSTGRES_DB: foodflow_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    profiles:
      - dev

  postgres-dev-audit:
    image: postgres:16
    container_name: postgres-dev-audit

    environment:
      POSTGRES_DB: foodflow_audit_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    profiles:
      - dev

  foodflow-api-dev:
    build: .
    container_name: foodflow-api-dev

    env_file:
      - .env.dev

    depends_on:
      - postgres-dev-main
      - postgres-dev-audit

    ports:
      - "8080:8080"

    profiles:
      - dev

  postgres-prod-main:
    image: postgres:16
    container_name: postgres-prod-main

    environment:
      POSTGRES_DB: foodflow_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_prod

    ports:
      - "5434:5432"

    profiles:
      - prod

  postgres-prod-audit:
    image: postgres:16
    container_name: postgres-prod-audit

    environment:
      POSTGRES_DB: foodflow_audit_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_prod

    ports:
      - "5435:5432"

    profiles:
      - prod

  foodflow-api-prod:
    build: .
    container_name: foodflow-api-prod

    env_file:
      - .env.prod

    depends_on:
      - postgres-prod-main
      - postgres-prod-audit

    ports:
      - "8081:8080"

    profiles:
      - prod