spring:
  config:
    activate:
      on-profile: prod

  datasource:
    jdbc-url: ${DB_MAIN_URL}
    username: ${DB_MAIN_USERNAME}
    password: ${DB_MAIN_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

audit:
  datasource:
    jdbc-url: ${DB_AUDIT_URL}
    username: ${DB_AUDIT_USERNAME}
    password: ${DB_AUDIT_PASSWORD}
    driver-class-name: org.postgresql.Driver